apiVersion: v1
kind: Service
metadata:
  name: openai-chatbot
  namespace: emiruzel-dev
  labels:
    app: openai-chatbot
spec:
  selector:
    app: openai-chatbot
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
